
// ---------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
using Ybm.Common.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Ybm.Business
{
    public interface IUserBusiness : Framework.Interface.IService<User>
    {
      
    }
}


